### ISSUE TITLE
Resized image size

### ISSUE THREAD

**Issue by Sergivs** [Nimrod007/PHP_image_resize#11]
Hi,

Is it possible to return the size of the new image?
If not, then how can I get it?

**Comment by Nimrod007** [comment]
by size what do you mean ?

**Comment by Nimrod007** [comment]
@Sergivs @kdamball - any updates?

**Comment by Sergivs** [comment]
@Nimrod007 
By "size" I mean image size.
So, for example, when you resize a file (the size of the original file is 500 kb), I'd would like to get the size of the resized file (new reaized file is now 300 kb).

**Comment by Nimrod007** [comment]
you have a native function for this (filesize)[http://php.net/filesize]

just use it on your resized image path 


```php
    //indicate which file to resize (can be any type jpg/png/gif/etc...)
      $file = 'your_path_to_file/file.png';

      //indicate the path and name for the new resized file
      $resizedFile = 'your_path_to_file/resizedFile.png';

      //call the function (when passing path to pic)
      smart_resize_image(bla bla bla...)
     
      //get resized image size
      echo filesize($resizedFile);

```

dont see a reason to add this to the function.
