### ISSUE TITLE
When resizing the image is rotated 90 degress counter clockwise

### ISSUE THREAD

**Issue by jakemwp** [Nimrod007/PHP_image_resize#9]
Hey guys, 

Pretty simple issue I think but I'm not sure what is causing it because I have been using this for a few months and this just started happening this week. 

Here is a link to the base image: http://67.227.192.13/~hosttestmyphpski/ftp-uploader/Front.jpg

Here is a link to the resized image: http://67.227.192.13/~hosttestmyphpski/ftp-uploader/resizedFrontjpg

Here is the code that I am using to generate this (where $filename is the path to the base image and $resizedFilename is the path to the re sized image):

    $resizedFilename = 'resized'.$filename;
    $resizedFilename = preg_replace("/[^A-Za-z0-9 ]/", '', $resizedFilename);;
    smart_resize_image($filename , null, 244 , 326 , false , $resizedFilename , false , false ,100 );

Any ideas what is causing this?

**Comment by mrhaw** [comment]
I suspect it's the EXIF data in play. What if you try rotating the picture couple of times and re-save it and reupload!
http://stackoverflow.com/a/33031994

**Comment by jakemwp** [comment]
Headed into a meeting, but I'll check on this as soon as I'm out give you an update.

**Comment by Nimrod007** [comment]
Hi @jakemwp can you update with result ? so I know if i can close this 1 ... thanks!

**Comment by jakemwp** [comment]
Definitely the EXIF data- had the client report another problem that was rotating the other direction. Ended up solving by changing file format to PNG to remove the EXIF data.
